### PR TITLE
NumberedRuneNames: add option to highlight hi level runes

### PR DESCRIPTION
**Pull request by AlexSnowLeo**
Highlight hi level runes (more than Starting Level 20 default) with purple color.

### CODE REVIEW

**Comment by olegbl** [comment]
Good idea, but I think this would be a better fit inside of [Custom Item Colors](https://www.nexusmods.com/diablo2resurrected/mods/190), allowing a user to specify different colors for LR vs MR vs HR.

**Comment by AlexSnowLeo** [comment]
> Good idea, but I think this would be a better fit inside of [Custom Item Colors](https://www.nexusmods.com/diablo2resurrected/mods/190), allowing a user to specify different colors for LR vs MR vs HR.

Hmm... OK. I'll try to implement this based on the 'Custom Item Colors' mod.

@olegbl please answer to another question. In another modification, which changes a large number of local data for the Russian language, I need to process a fairly large array of data and it is not convenient to specify them directly in the mod code. How can I read the JSON mod that lies locally?
image

**Comment by olegbl** [comment]
You can probably include the JSON file with your mod, copy it to the output directory with `D2RMM.copyFile`, then read it with `D2RMM.readJson`.

In a future release of D2RMM, you'd also just be able to run `import`, but support for multi-file mods and TypeScript isn't quite ready to be released yet.

**Comment by AlexSnowLeo** [comment]
> You can probably include the JSON file with your mod, copy it to the output directory with `D2RMM.copyFile`, then read it with `D2RMM.readJson`.
> 
> In a future release of D2RMM, you'd also just be able to run `import`, but support for multi-file mods and TypeScript isn't quite ready to be released yet.

It not works :(

> Mod RuLocalizationFix encountered an error! Error: API.extractFile: Failed to open file in CASC storage (local\lng\strings\item-names.diffs.json): (CascLib Error Code: 2) at mod.js:28:29 at mod.js:43:3 at VM.runScript (D:\Downloads\Games\D2\D2RMM 1.5.0\resources\app.asar\node_modules\vm2\lib\mod.js:287:18) at D:\Downloads\Games\D2\D2RMM 1.5.0\resources\app.asar\node_modules\vm2\lib\mod.js:511:1
> 11:23:43

Sample code:
```
D2RMM.copyFile(
  'local', // <mod folder>\local
  'local', // <diablo 2 folder>\mods\D2RMM\D2RMM.mpq\data\local
  true // overwrite any conflicts
);

const itemNamesDiff = D2RMM.readJson('local\\lng\\strings\\item-names.diffs.json');
```

**Comment by AlexSnowLeo** [comment]
> Good idea, but I think this would be a better fit inside of [Custom Item Colors](https://www.nexusmods.com/diablo2resurrected/mods/190), allowing a user to specify different colors for LR vs MR vs HR.

Another clarification of **the CustomItemColor mod only changes the color of the tooltip, that is, the item on the ground, but not in the inventory**.

In `_profilehd.json` it is possible to specify only 'RuneColor' without dividing into levels:
image

**Comment by olegbl** [comment]
> It not works :(

Ah, because it doesn't realize that file already exists since it wasn't explicitly written, so it tries to read it from the game files instead of the generated mod files.

Try something like:

```
D2RMM.writeJson('local\\lng\\strings\\item-names.diffs.json', {});
D2RMM.copyFile(
  'local', // <mod folder>\local
  'local', // <diablo 2 folder>\mods\D2RMM\D2RMM.mpq\data\local
  true // overwrite any conflicts
);
const itemNamesDiff = D2RMM.readJson('local\\lng\\strings\\item-names.diffs.json');
```

> In _profilehd.json it is possible to specify only 'RuneColor' without dividing into levels

Yup. You'd have to stick the coloring into the localization files to separate LR/MR/HR colors. Runes is one of the item types that this is possible for though.

**Comment by AlexSnowLeo** [comment]
> > It not works :(
> 
> Ah, because it doesn't realize that file already exists since it wasn't explicitly written, so it tries to read it from the game files instead of the generated mod files.
> 
> Try something like:

But again error:

```
2024-02-20T18:42:18.133Z,debug,Mod RuLocalizationFix installing...
2024-02-20T18:42:18.133Z,debug,BridgeAPI.writeFile {"inputPath":"d:\\Games\\Diablo II Resurrected\\mods\\D2RMM\\D2RMM.mpq\\data\\local\\lng\\strings\\item-names.diffs.json","isRelative":false}
2024-02-20T18:42:18.133Z,error,BridgeAPI.writeJson {}
2024-02-20T18:42:18.133Z,error,Mod RuLocalizationFix encountered an error!
Error: BridgeAPI.writeFile: Failed to write file: Error: ENOENT: no such file or directory, open 'd:\Games\Diablo II Resurrected\mods\D2RMM\D2RMM.mpq\data\local\lng\strings\item-names.diffs.json'
    at mod.js:1:7
    at mod.js:45:3
    at VM.runScript (D:\Downloads\Games\D2\D2RMM 1.5.0\resources\app.asar\node_modules\vm2\lib\mod.js:287:18)
    at D:\Downloads\Games\D2\D2RMM 1.5.0\resources\app.asar\node_modules\vm2\lib\mod.js:511:1
```

**Comment by olegbl** [comment]
Ah. It's a little awkward to do right now (I'll need to think about a way to improve the API for this use case):
```
// copy the file so that it exists
D2RMM.copyFile(
  'local', // <mod folder>\local
  'local', // <diablo 2 folder>\mods\D2RMM\D2RMM.mpq\data\local
  true // overwrite any conflicts
);

// overwrite it so D2RMM knows it exists in mod output
D2RMM.writeJson('local\\lng\\strings\\item-names.diffs.json', {});

// copy the file again to update its contents
D2RMM.copyFile(
  'local', // <mod folder>\local
  'local', // <diablo 2 folder>\mods\D2RMM\D2RMM.mpq\data\local
  true // overwrite any conflicts
);

// read the file
const data = D2RMM.readJson('local\\lng\\strings\\item-names.diffs.json');
console.log(data);
```

I should probably make `D2RMM.copyFile` mark all copied files as having been extracted.

**Comment by AlexSnowLeo** [comment]
> Ah. It's a little awkward to do right now (I'll need to think about a way to improve the API for this use case):

The same error:
```
2024-02-21T04:20:44.986Z,debug,Mod RuLocalizationFix installing...
2024-02-21T04:20:44.986Z,debug,BridgeAPI.writeFile {"inputPath":"d:\\Games\\Diablo II Resurrected\\mods\\D2RMM\\D2RMM.mpq\\data\\local\\lng\\strings\\item-names.diffs.json","isRelative":false}
2024-02-21T04:20:44.986Z,error,BridgeAPI.writeJson {}
2024-02-21T04:20:44.986Z,error,Mod RuLocalizationFix encountered an error!
Error: BridgeAPI.writeFile: Failed to write file: Error: ENOENT: no such file or directory, open 'd:\Games\Diablo II Resurrected\mods\D2RMM\D2RMM.mpq\data\local\lng\strings\item-names.diffs.json'
    at mod.js:1:7
    at mod.js:45:3
    at VM.runScript (D:\Downloads\Games\D2\D2RMM 1.5.0\resources\app.asar\node_modules\vm2\lib\mod.js:287:18)
    at D:\Downloads\Games\D2\D2RMM 1.5.0\resources\app.asar\node_modules\vm2\lib\mod.js:511:1
```

**Comment by AlexSnowLeo** [comment]
@olegbl "It's alive!!!' 😁 Everything worked. Thank you very much! If you specify a place where to finalize the 'D2RMM.CopyFile', I will try to do it in a separate PR.

**Comment by AlexSnowLeo** [comment]
@olegbl what about updates in this PR? Can they be applied to the current mod?
Or do I need to implement this:
>Yup. You'd have to stick the coloring into the localization files to separate LR/MR/HR colors. Runes is one of the item types that this is possible for though.

**Comment by olegbl** [comment]
I think this PR can be abandoned in favor of #16 (yes, with the localization file changes).

Basically, what I said earlier:

> I think this would be a better fit inside of [Custom Item Colors](https://www.nexusmods.com/diablo2resurrected/mods/190), allowing a user to specify different colors for LR vs MR vs HR.

i.e. I don't think Numbered Rune Names is the right place for this feature.

**Comment by olegbl** [comment]
> Ah. It's a little awkward to do right now (I'll need to think about a way to improve the API for this use case)

https://github.com/olegbl/d2rmm/commit/ab994f02bae945fc5c30194dbdbc08441fe30205 fixes this issue.

After this change,
```
// copy the file so that it exists
D2RMM.copyFile(
  'local', // <mod folder>\local
  'local', // <diablo 2 folder>\mods\D2RMM\D2RMM.mpq\data\local
  true // overwrite any conflicts
);

// read the file
const data = D2RMM.readJson('local\\lng\\strings\\item-names.diffs.json');
console.log(data);
```
should be sufficient.

**Pull request closed without merging**
