### PR TITLE
DisableBattleNet: remove online/offline tabs in character select panel

### PR DESCRIPTION
**Pull request by anzz1**
DisableBattleNet: remove online/offline tabs in character select panel

### CODE REVIEW

**Comment by anzz1** [comment]
If want to make it extra nice, I guess one could concat a text widget with "Character select" or whatever in the empty space left by Online/Offline tabs, but it looks fine as-is.

**Comment by eleriaqueen** [comment]
Nice job.
Pictures of the current implementation for reference:

Before / Default
Screenshot_20240108_034924z

After / Modded
Screenshot_20240108_034838z

**Comment by eleriaqueen** [comment]
Something like this very amateurish concat could fill (part of) the void left by the Tab Widget. 
```
.concat([{
  type: 'TabBarWidget',
  name: 'Characters',
  fields: {
    rect: {
      x: 292,
      y: 29
    },
    tabCount: 1,
    filename: 'FrontEnd\\HD\\Final\\FrontEnd_Tabs',
    inactiveFrames: [1, 1],
    activeFrames: [0, 0],
    disabledFrames: [2, -1],
    textStrings: ['Characters'],
    textStyle: {
      pointSize: '$MediumLargeFontSize'
    },
    activeTextColor: '$TabsActiveTextColor',
    inactiveTextColor: '$TabsInactiveTextColor',
    disabledTextColor: '$FontColorGray',
    tabSize: {
      x: 332,
      y: 71
    },
    tabPadding: {
      x: -1,
      y: 0
    },
    automaticallyPositionIndicators: true,
  }
}, ])
```

Screenshot_20240108_062615

**Comment by Caedendi** [comment]
I think it would look better if that single "Characters" tab would take up the entire width instead of being centered. 

Is this PR still alive? It's been open for like half a year now.

**Comment by anzz1** [comment]
I'm not exactly sure what you mean by 'alive', but if that means:
"is this PR still up-to-date and ready to be merged?", the answer is yes.
"is this PR work-in-progress and am I going to add something to it?", the answer is no.

The author is probably just busy, PRs being open for long times happen all the time.

**Comment by olegbl** [comment]
Thank you for your contribution! I have incorporated it into the mod with some changes in 5d646bd8c2699fc24002eb58756f3a8879d0db65.

image

**Pull request closed without merging**
